products = [
    {
      '_id': '1',
      'name': 'Sky Qweller-4000',
      'image': '/images/list/Sky Qweller-4000.jpg',
      'imageDetails': '/images/details/Sky Qweller-4000.png',
      'description':
        'What looked like a small patch of purple grass, above five feet square wan.',
      'brand': 'Seiko',
      'category': 'Luxury Watches',
      'price': 2115,
      'countInStock': 10,
      'rating': 4.5,
      'numReviews': 12,
    },
    {
      '_id': '2',
      'name': 'Day Date-820',
      'image': '/images/list/Day Date-820.jpg',
      'imageDetails': '/images/details/Day Date-820.png',
      'description':
        'No looked like a small patch of purple grass, above five feet square wan.',
      'brand': 'Citizen',
      'category': 'Casual Watches',
      'price': 1200,
      'countInStock': 0,
      'rating': 4.0,
      'numReviews': 8,
    },
    {
      '_id': '3',
      'name': 'Date Just-6500',
      'image': '/images/list/Date Just-6500.jpg',
      'imageDetails': '/images/details/Date Just-6500.png',
      'description':
        'What looked like a small patch of purple grass, above five feet square wan.',
      'brand': 'Cartier',
      'category': 'Luxury Watches',
      'price': 3000,
      'countInStock': 5,
      'rating': 3,
      'numReviews': 12,
    },
    {
      '_id': '4',
      'name': 'Sports Master-400',
      'image': '/images/list/Sports Master-400.jpg',
      'imageDetails': '/images/details/Sports Master-400.png',
      'description':
        'What looked like a small patch of purple grass, above five feet square wan.',
      'brand': 'Casio',
      'category': 'Casual Watches',
      'price': 800,
      'countInStock': 11,
      'rating': 5,
      'numReviews': 12,
    },
    {
      '_id': '5',
      'name': 'Pearl Master-600',
      'image': '/images/list/Pearl Master-600.jpg',
      'imageDetails': '/images/details/Pearl Master-600.png',
      'description':
        'No looked like a small patch of purple grass, above five feet square wan.',
      'brand': 'Titan',
      'category': 'Casual Watches',
      'price': 1000,
      'countInStock': 7,
      'rating': 3.5,
      'numReviews': 10,
    },
    {
      '_id': '6',
      'name': 'Just Sports-200',
      'image': '/images/list/Just Sports-200.jpg',
      'imageDetails': '/images/details/Just Sports-200.png',
      'description':
        'No looked like a small patch of purple grass, above five feet square wan.',
      'brand': 'Nike',
      'category': 'Casual Watches',
      'price': 600,
      'countInStock': 0,
      'rating': 4,
      'numReviews': 12,
    },
  ]