export const CART_ADD_ITEM = "CART_ADD_ITEM" 
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM" 
export const CART_INCREASE_QTY = "CART_INCREASE_QTY" 
export const CART_DECREASE_QTY = "CART_DECREASE_QTY" 