# Generated by Django 4.1.1 on 2022-10-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_image_product_imagedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/watch_image_default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageDetails',
            field=models.ImageField(blank=True, default='/watch_image_details_default.png', null=True, upload_to=''),
        ),
    ]
